### ISSUE TITLE
Condition is not re-checked if Callable<Boolean> passed to until(Callable<Boolean>) throws

### ISSUE THREAD

**Issue by tazle** [awaitility/awaitility#78]
(This is verified on 1.7.0, I have not tested 2.0.0, but at least the documentation has not changed)

The following three test cases have different behaviour.

The first one rethrows the exception immediately. The second one swallows the exception, waits for 10 seconds, then rethrows it. The third one succeeds.

I would expect that at least the latter two cases would succeed, since handling of AssertionFailedErrors is clearly already special, and arguably also the first one should succeed, since the API documentation of `until(Callable<Boolean>)` does not say anything about passing through exceptions, and some exceptions are already handled in special manner.

```
public class AwaitTest {
    @Test
    public void testUntilCallableBoolean_RuntimeException() {
        final AtomicInteger counter = new AtomicInteger(0);
        await().atMost(10, TimeUnit.SECONDS).until(() -> {
            if (counter.get() < 2) {
                counter.incrementAndGet();
                throw new RuntimeException("Not yet");
            } else {
                return true;
            }
        });
    }

    @Test
    public void testUntilCallableBoolean_AssertionFailedError() {
        final AtomicInteger counter = new AtomicInteger(0);
        await().atMost(10, TimeUnit.SECONDS).until(() -> {
            counter.incrementAndGet();
            assertTrue(counter.get() >= 2);
            return true;
        });
    }

    @Test
    public void testUntilRunnable() {
        final AtomicInteger counter = new AtomicInteger(0);
        await().atMost(10, TimeUnit.SECONDS).until(() -> {
            counter.incrementAndGet();
            assertTrue(counter.get() >= 2);
        });
    }
}
```

**Comment by johanhaleby** [comment]
I can see that this is confusing. Let me brake it down.

1. This example throws an exception which will fail the test immediately since you haven't [configured awaitility to ignore it](https://github.com/awaitility/awaitility/wiki/Usage#example-9---ignoring-exceptions).
1. This is a bit spooky, because the lambda to Awaitility doesn't have the same type as the lambda in example 3. It expects a predicate and predicates shouldn't have side-effects (at least not side effects that throws exceptions). But this is not possible to declare in Java's type system. Maybe this could be regarded as a bug because if the Condition is of type Boolean an exception/error should always fail the test (unless ignored) imho.
1. This example doesn't throw an exception, it throws an `AssertionError`. `AsserttionError`'s are handled specially so that Awaitility can interop with other assertion libraries such as assertj (see [docs](https://github.com/awaitility/awaitility/wiki/Usage#example-8---using-assertj-or-fest-assert)). Ignoring `AssertionError`'s is the way Awaitility currently supports these third-party assertion libraries

**Comment by tazle** [comment]
Hm, yes, AssertionError is indeed not Exception.

You did not comment on the fact that case 2 continues to wait until timeout but does not retry the predicate calls. What's the point of waiting if there are no retries?

**Comment by johanhaleby** [comment]
I think this is a bug. I'm about to change the method name for the method accepting "Runnable" since it's causing other problems as well (for groovy and kotlin) besides being confusing. 

I'll hopefully release a 3.0.0-rc1 today.

The method will now be called `untilAsserted` instead (other suggestions are welcome).

**Comment by johanhaleby** [comment]
It was indeed a bug (that I've now fixed) that the exception didn't break the poll execution in example 2.
