### ISSUE TITLE
Ignore Throwables

### ISSUE THREAD

**Issue by mkopylec** [awaitility/awaitility#85]
Methods for ignoring exceptions should have `Class<Throwable>` arguments

**Comment by johanhaleby** [comment]
What your use case?

**Comment by mkopylec** [comment]
There is a tool called [WireMock](https://github.com/tomakehurst/wiremock) and it has [VerificationException](https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/client/VerificationException.java) which does not inherit `Exception`

**Comment by johanhaleby** [comment]
Thanks. I think I tried to use Throwable at first but there was some problems with it. Can't remember what it was though. Maybe have to look into this again.

**Comment by johanhaleby** [comment]
I've now looked into this again and the reason why I didn't just change to throwable before was that it introduces a non-backward compatible change if not using Java 8 lambda expressions. But since I'm about to release a new major version I've now fixed this and introduced the possible non-backward compatible change. I've now deployed a new snapshot that should address this issue. Please try version `3.0.0-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by mkopylec** [comment]
Great, I'll check that out. Waiting for a full 3.0.0 release.
