### ISSUE TITLE
Cannot use awiat multiple times when having Awaitility.pollInSameThread()

### ISSUE THREAD

**Issue by javornikolov** [awaitility/awaitility#89]
In the below fragment  only the 1st from the two await().untilAsserted(...) calls is executed:

``` java
        Awaitility.pollInSameThread();

        await().untilAsserted(() -> {
            System.out.println("checking stuff 1...");
            assertThat("1234").isEqualTo("1234");
        });

        await().untilAsserted(() -> {
            System.out.println("checking stuff 2..."); // This is never reached
            assertThat("1234").isEqualTo("1234");
        });
```

The problem seems to be that the `SameThreadExecutor` instance which is created upon `pollInSameThread` mutates after the 1st execution and cannot be reused after that.

**Comment by johanhaleby** [comment]
Thanks for reporting, looks like quite a serious bug.

**Comment by mjiderhamn** [comment]
`org.awaitility.core.ConditionAwaiter.await()` invokes `executor.shutdown()` in a `finally` block, so that upon the next use `!executor.isShutdown()` immediately evaluates to `false`.

The code for this was changed with #101 (commit 1dcbfb3f916d76545cf25ee346a2e8d0c6042861 ) but I haven't verified whether this particular issue was fixed too.

**Comment by johanhaleby** [comment]
@mjiderhamn Thanks for bring this to our attention. Yes this should be closed afaik.
